style.fill: transparent

step_mom: {
    label: Timestep
}

step_mom -> step_mom_dynamics
step_mom -> step_mom_thermo
step_mom -> ale_regridding_and_remapping
step_mom -> step_mom_tracer_dyn

# Dycore

step_mom_dynamics: {
    label: Dynamics
}

step_mom_dynamics -> step_mom_dyn_split_RK2
step_mom_dynamics -> calc_slope_functions
step_mom_dynamics -> thickness_diffuse
step_mom_dynamics -> set_viscous_BBL
step_mom_dynamics -> mixedlayer_restrat

step_mom_dyn_split_RK2: {
    label: RK2
}

calc_slope_functions -> calc_isoneutral_slopes
calc_slope_functions -> valc_visbeck_coeffs_old

# Thermo

step_mom_thermo -> diabatic
diabatic -> energetic_PBL
diabatic -> set_diffusivity
diabatic -> applyboundaryfluxesinout

# ALE

ale_regridding_and_remapping: {
    label: ALE
}

# Tracers

step_mom_tracer_dyn: {
    label: Tracers
}

step_mom_tracer_dyn -> advect_tracer
step_mom_tracer_dyn -> tracer_hordiff
step_mom_tracer_dyn -> tracer_vertdiff
